POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password": "test"
}

###

POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password": "test"
}

###

GET http://localhost:3000/api/auth/secret
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJwcm9zdGdtNCIsInN1YiI6IjVlYTE5NmVkY2UzNTRlNTE1OGVjNjVjMCIsImlhdCI6MTU4NzY0ODIzNzY2NiwiZXhwIjoxNTg3NzM0NjM3NjY2fQ.ewZfPsHHtpKH8Vds4PhusSRChrAjsSsv02Folf5URsA
