POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "email": "lulu@gmail.com",
    "password": "mario"
}

###

POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "lulu@gmail.com",
    "password": "mario"
}

###

GET http://localhost:3000/api/auth/secret
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJwcm9zdGdtNCIsInN1YiI6IjVlYTE3OWZjYzBmNDQzNTYzODg2YTdhNyIsImlhdCI6MTU4NzY0MDgzNzc0OSwiZXhwIjoxNTg3NzI3MjM3NzQ5fQ.sbsRH0l-kfUSvtJLrDEVzv1wjWlcgHnphQeCZ0uTp_w
