export const REGISTER = 'register'
export const LOGIN = 'login'
export const ERROR = 'error'
export const ERROR_LOGIN = 'error_login'
export const RESET_ERROR = 'reset error'
export const SUCCESS = 'success'
export const REDIRECT = 'redirect'